name: Bug Report
title: "Bug: "
description: Report a bug to help us improve
type: "Bug"
projects: ["onHandTech/5"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report

        **Formatting help**: [GitHub Markdown Guide](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this bug?
      options:
        - P1 - Critical (blocks development/production)
        - P2 - High (major issue, workaround exists)
        - P3 - Medium (minor issue)
        - P4 - Low (cosmetic or edge case)

  - type: textarea
    id: description
    attributes:
      label: What's the bug?
      placeholder: Describe the issue and what you expected to happen

  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error