name: Spike Ticket
title: "Spike: "
description: Create a spike for research and investigation
labels: ["spike"]
type: "Feature"
projects: ["onHandTech/5"]
body:
  - type: markdown
    attributes:
      value: |
        ## Spike Ticket
        Time-boxed research and investigation.

        **Formatting help**: [GitHub Markdown Guide](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)

  - type: textarea
    id: overview
    attributes:
      label: What are we investigating?
      placeholder: Describe what needs research and what questions need answers

  - type: input
    id: timebox
    attributes:
      label: Time Box
      placeholder: e.g., 2 days, 1 sprint