name: Tech Ticket
title: "Tech: "
description: Create a technical task or improvement ticket
labels: ["tech-debt"]
type: "Task"
projects: ["onHandTech/5"]
body:
  - type: markdown
    attributes:
      value: |
        ## Technical Ticket
        For technical improvements, refactoring, tech debt, or infrastructure work.

        **Formatting help**: [GitHub Markdown Guide](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)

  - type: dropdown
    id: tech_type
    attributes:
      label: Type of Technical Work
      description: What category does this work fall into?
      options:
        - Tech Debt
        - Refactoring
        - Performance Optimization
        - Infrastructure/DevOps
        - Security
        - Testing/Quality
        - Tooling/DX
        - Dependency Updates
        - Documentation

  - type: textarea
    id: description
    attributes:
      label: What needs to be done?
      placeholder: Describe the technical work and why it's needed

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
