name: Ticket
title: "Ticket: "
description: Create a feature request or general task ticket
type: "Task"
projects: ["onHandTech/5"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature/Task Ticket
        For feature requests, user stories, or general development tasks.

        **Formatting help**: [GitHub Markdown Guide](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)

  - type: textarea
    id: description
    attributes:
      label: What needs to be built?
      placeholder: Describe the feature or task and why it's needed

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
